build:
	docker-compose build

up:
	docker-compose up

migrate:
	npm run migrate:up

logs:
	docker-compose logs -f

ps:
	docker ps

up-prod:
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

down:
	docker-compose down